In [1]:
from __future__ import print_function
import torch


In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  1.7096e-42,  0.0000e+00],
        [ 0.0000e+00,  6.7131e+22,  0.0000e+00]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[ 0.7595,  0.6016,  0.8782],
        [ 0.5782,  0.6500,  0.8668],
        [ 0.0991,  0.8795,  0.0244],
        [ 0.5168,  0.1867,  0.3347],
        [ 0.0951,  0.6331,  0.0676]])


In [4]:
x = torch.zeros(5,3, dtype= torch.long)
x

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])

In [5]:
# tensor from data
x = torch.tensor([5.4,3])
x

tensor([ 5.4000,  3.0000])

In [6]:
print(x.size())

torch.Size([2])


In [7]:
x = x.new_ones(5,3,dtype = torch.double)
print(x)

x = torch.rand_like(x,dtype = torch.float)
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)
tensor([[ 0.5009,  0.9561,  0.8695],
        [ 0.8476,  0.1461,  0.1307],
        [ 0.0049,  0.9680,  0.6554],
        [ 0.4728,  0.1491,  0.7985],
        [ 0.7728,  0.2481,  0.1282]])


## **torch.Size is in fact a tuple, so it supports all tuple operations.**

# OPERATIONS

## Addition:

In [8]:
y = torch.rand(5,3)
print(x+y)
#syntax 2
print(torch.add(x,y))

tensor([[ 0.8632,  1.6311,  1.5397],
        [ 0.8568,  0.2618,  0.3956],
        [ 0.2646,  1.5530,  1.1225],
        [ 0.5092,  0.2128,  1.3652],
        [ 1.1425,  0.8027,  0.2636]])
tensor([[ 0.8632,  1.6311,  1.5397],
        [ 0.8568,  0.2618,  0.3956],
        [ 0.2646,  1.5530,  1.1225],
        [ 0.5092,  0.2128,  1.3652],
        [ 1.1425,  0.8027,  0.2636]])


In [9]:
result = torch.Tensor(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[ 0.8632,  1.6311,  1.5397],
        [ 0.8568,  0.2618,  0.3956],
        [ 0.2646,  1.5530,  1.1225],
        [ 0.5092,  0.2128,  1.3652],
        [ 1.1425,  0.8027,  0.2636]])


In [10]:
res = x+y
print(res)

tensor([[ 0.8632,  1.6311,  1.5397],
        [ 0.8568,  0.2618,  0.3956],
        [ 0.2646,  1.5530,  1.1225],
        [ 0.5092,  0.2128,  1.3652],
        [ 1.1425,  0.8027,  0.2636]])


In [11]:
# inplace addition
y.add_(x)
print(y)

tensor([[ 0.8632,  1.6311,  1.5397],
        [ 0.8568,  0.2618,  0.3956],
        [ 0.2646,  1.5530,  1.1225],
        [ 0.5092,  0.2128,  1.3652],
        [ 1.1425,  0.8027,  0.2636]])


**Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.**

In [12]:
print(x[:,1])

tensor([ 0.9561,  0.1461,  0.9680,  0.1491,  0.2481])


# Resizing

In [13]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8) # the size -1 is means it is inferred from other dimensions
print(x.size(),y.size(),z.size())


torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [14]:
# if we have one element tensor use .item() to get the value as python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([ 0.8411])
0.8411468863487244


# NumPy Bridge

In [15]:
# converting a torch tensor to Numpy Array or vice versoa

a = torch.ones(5)
print(a)


tensor([ 1.,  1.,  1.,  1.,  1.])


In [16]:
b = a.numpy() # does not creat a deep copy 
print(b)

[1. 1. 1. 1. 1.]


#### see how the numpy array changed in value


In [17]:
a.add_(1)
print(a)
print(b)

tensor([ 2.,  2.,  2.,  2.,  2.])
[2. 2. 2. 2. 2.]


## Converting Numpy Array to torch tensor

In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


In [20]:
x = torch.randn(4000,4000,dtype=torch.float)
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device = device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to("cpu",torch.double))


tensor([[ 9.1678e-01,  8.8360e-01,  2.6719e+00,  ...,  1.3667e+00,
         -1.9552e-01,  1.7211e+00],
        [ 8.0886e-01,  1.2551e+00,  2.2363e+00,  ...,  1.1818e-01,
          2.0135e+00,  1.8479e+00],
        [ 1.9555e+00,  1.1531e+00,  1.3150e+00,  ...,  3.4733e-01,
          3.6839e-01,  6.8990e-01],
        ...,
        [ 2.9932e-01,  8.0197e-01,  4.6812e-01,  ...,  4.8632e-01,
         -4.1090e-01,  2.1019e+00],
        [ 1.7009e+00,  3.5408e+00,  8.1334e-01,  ...,  2.5536e+00,
          1.1481e+00,  1.5949e+00],
        [ 7.6551e-01,  5.4000e-01,  2.0742e+00,  ...,  1.3310e+00,
         -2.8008e-01,  6.8970e-01]], device='cuda:0')
tensor([[ 9.1678e-01,  8.8360e-01,  2.6719e+00,  ...,  1.3667e+00,
         -1.9552e-01,  1.7211e+00],
        [ 8.0886e-01,  1.2551e+00,  2.2363e+00,  ...,  1.1818e-01,
          2.0135e+00,  1.8479e+00],
        [ 1.9555e+00,  1.1531e+00,  1.3150e+00,  ...,  3.4733e-01,
          3.6839e-01,  6.8990e-01],
        ...,
        [ 2.9932e-01,  8.0197